import { useState } from "react";
import { motion } from "framer-motion";
import { Building2, TrendingDown, Check, CircleCheck } from "lucide-react";
import { toast } from "sonner";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { RECOMMENDATIONS } from "@/lib/appData";

export default function RecommendationsPage() {
  const [accepted, setAccepted] = useState([]);
  const [completed, setCompleted] = useState([]);
  const [assigned, setAssigned] = useState([]);
  const [escalated, setEscalated] = useState([]);

  const act = (setter, id, msg) => {
    setter((s) => [...new Set([...s, id])]);
    toast.success(msg);
  };

  return (
    <DashboardShell
      testId="recommendations-page"
      crumb="AI Recommendations"
      title="AI Recommended Actions"
      subtitle="Prioritized interventions generated by the recommendation engine to reduce delay risk"
    >
      <div className="space-y-4" data-testid="recommendations-list">
        {RECOMMENDATIONS.map((r, i) => {
          const isCompleted = completed.includes(r.id);
          const isAccepted = accepted.includes(r.id);
          return (
            <motion.div
              key={r.id}
              initial={{ opacity: 0, y: 18 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: i * 0.08, ease: [0.22, 1, 0.36, 1] }}
              whileHover={{ y: -3 }}
              className="rounded-2xl border border-slate-200/80 bg-white/95 p-5 backdrop-blur-sm"
              data-testid={`recommendation-${r.id}`}
            >
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div className="flex items-start gap-4">
                  <div className="font-display flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[#0B3D91] text-sm font-extrabold text-white">
                    {r.id}
                  </div>
                  <div>
                    <div className="flex flex-wrap items-center gap-2">
                      <p className="text-sm font-bold text-slate-900">{r.title}</p>
                      {isAccepted && (
                        <span className="flex items-center gap-1 rounded-md border border-blue-200 bg-blue-50 px-2 py-0.5 text-[10px] font-extrabold uppercase tracking-wider text-blue-700">
                          <Check className="h-3 w-3" /> Accepted
                        </span>
                      )}
                      {isCompleted && (
                        <span className="flex items-center gap-1 rounded-md border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[10px] font-extrabold uppercase tracking-wider text-emerald-700">
                          <CircleCheck className="h-3 w-3" /> Completed
                        </span>
                      )}
                    </div>
                    <p className="mt-1 text-sm text-slate-600">{r.detail}</p>
                    <div className="mt-2 flex flex-wrap items-center gap-4 text-xs font-semibold text-slate-500">
                      <span className="flex items-center gap-1.5"><Building2 className="h-3.5 w-3.5" /> {r.dept}</span>
                      <span className="flex items-center gap-1.5 text-emerald-600"><TrendingDown className="h-3.5 w-3.5" /> {r.impact}</span>
                    </div>
                  </div>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <button
                    data-testid={`rec-accept-${r.id}`}
                    onClick={() => act(setAccepted, r.id, `${r.id} accepted — added to execution plan`)}
                    className="rounded-lg bg-[#0B3D91] px-3.5 py-2 text-xs font-bold text-white transition-colors hover:bg-[#09337A]"
                  >
                    {isAccepted ? "Accepted" : "Accept"}
                  </button>
                  <button
                    data-testid={`rec-assign-${r.id}`}
                    onClick={() => act(setAssigned, r.id, `${r.id} assigned to ${r.dept}`)}
                    className="rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-bold text-slate-600 transition-colors hover:border-[#0B3D91]/40 hover:text-[#0B3D91]"
                  >
                    {assigned.includes(r.id) ? "Assigned" : "Assign"}
                  </button>
                  <button
                    data-testid={`rec-complete-${r.id}`}
                    onClick={() => act(setCompleted, r.id, `${r.id} marked complete`)}
                    className="rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-bold text-slate-600 transition-colors hover:border-emerald-300 hover:text-emerald-600"
                  >
                    {isCompleted ? "Completed" : "Mark Complete"}
                  </button>
                  <button
                    data-testid={`rec-escalate-${r.id}`}
                    onClick={() => act(setEscalated, r.id, `${r.id} escalated`)}
                    className="rounded-lg border border-slate-200 bg-white px-3.5 py-2 text-xs font-bold text-slate-600 transition-colors hover:border-orange-300 hover:text-orange-600"
                  >
                    {escalated.includes(r.id) ? "Escalated" : "Escalate"}
                  </button>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </DashboardShell>
  );
}
